apiVersion: v1
kind: Pod
metadata:
  name: nginx # This is just like apache that do web server configuration same as apache different company
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
